### ISSUE TITLE
infografia luis gerardo

### ISSUE THREAD

**Issue by LuisGerardo814** [SistemasTecTlaxiaco/infografia-LuisGerardo814#1]
[RealidadAumentada_LuisGeardoOrtizGonzalez.pdf](https://github.com/SistemasTecTlaxiaco/infografia-LuisGerardo814/files/6184493/RealidadAumentada_LuisGeardoOrtizGonzalez.pdf)

**Comment by ObedG** [comment]
Calificación: 17

**Comment by josealfredo79** [comment]
Esta bien hecho..falta mas diseño a la infografia.
